version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'ruok' | nc localhost 2181" ]
      interval: 10s
      timeout: 5s
      retries: 5

  broker-kafka1:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker1-kafka1
    container_name: broker-kafka1
    ports:
      - "9095:9095"
      - "29095:29095"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2182"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_KEK://broker-kafka1:29095, LISTENER_KEK://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_KEK
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    healthcheck:
      test: ["CMD", "bash", "-c", "nc -z localhost 9095" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER : kekuser
      POSTGRES_PASSWORD : kekpwd
      POSTGRES_DB : kekstradb
    healthcheck:
      test: ["CMD", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5  

  # broker-kafka2:
  #   image: confluentinc/cp-kafka:7.4.0
  #   hostname: broker2-kafka2
  #   container_name: broker-kafka2
  #   ports:
  #     - "9093:9093"
  #     - "29093:29093"
  #   environment:
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-kafka2:19093,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9093,DOCKER://host.docker.internal:29093
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2182"
  #     KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
  #     KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
  #     KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
  #   healthcheck:
  #     test: ["CMD", "bash", "-c", "nc -z localhost 9093" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - kafka-network
  #     - airflow-kafka

  # broker-kafka3:
  #   image: confluentinc/cp-kafka:7.4.0
  #   hostname: broker3-kafka3
  #   container_name: broker-kafka3
  #   ports:
  #     - "9094:9094"
  #     - "29094:29094"
  #   environment:
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker-kafka3:19094,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9094,DOCKER://host.docker.internal:29094
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2182"
  #     KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
  #     KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
  #     KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
  #   healthcheck:
  #     test: ["CMD", "bash", "-c", "nc -z localhost 9094" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - kafka-network
  #     - airflow-kafka

  # kafka-connect:
  #   image: confluentinc/cp-kafka-connect:7.4.0
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     CONNECT_BOOTSTRAP_SERVERS: broker-kafka1:19095,broker-kafka2:19093,broker-kafka3:19094
  #     CONNECT_REST_PORT: 8083
  #     CONNECT_GROUP_ID: compose-connect-group
  #     CONNECT_CONFIG_STORAGE_TOPIC: compose-connect-configs
  #     CONNECT_OFFSET_STORAGE_TOPIC: compose-connect-offsets
  #     CONNECT_STATUS_STORAGE_TOPIC: compose-connect-status
  #     CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
  #     CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
  #     CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  #     CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
  #     CONNECT_REST_ADVERTISED_HOST_NAME: 'kafka-connect'
  #     CONNECT_LOG4J_ROOT_LOGLEVEL: 'INFO'
  #     CONNECT_LOG4J_LOGGERS: 'org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR'
  #     CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components'
  #   networks:
  #     - kafka-network
  #     - airflow-kafka

  # schema-registry:
  #   image: confluentinc/cp-schema-registry:7.3.2
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker-kafka1:19095,broker-kafka2:19093,broker-kafka3:19094
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  #   networks:
  #     - kafka-network
  #     - airflow-kafka

  # kafka-ui:
  #   container_name: kafka-ui
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - 8888:8080 # Changed to avoid port clash with akhq
  #   depends_on:
  #     - broker-kafka1
  #     - broker-kafka2
  #     - broker-kafka3
  #     - schema-registry
  #     - kafka-connect
  #   environment:
  #     KAFKA_CLUSTERS_0_NAME: local
  #     KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: PLAINTEXT://broker-kafka1:19095,PLAINTEXT_HOST://broker-kafka1:19095
  #     KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
  #     KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: connect
  #     KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://kafka-connect:8083
  #     DYNAMIC_CONFIG_ENABLED: 'true'
  #   networks:
  #     - kafka-network
  #     - airflow-kafka

  # spark:
  #   image: bitnami/spark:3
  #   container_name: spark_master
  #   ports:
  #     - 8085:8080
  #   environment:
  #     - SPARK_UI_PORT=8080
  #     - SPARK_MODE=master
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #   networks:
  #     - airflow-kafka
  #     - kafka-network

  # postgres:
  #   image: postgres:latest
  #   container_name: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER : kekuser
  #     POSTGRES_PASSWORD : kekpwd
  #     POSTGRES_DB : votingDB
  #   healthcheck:
  #     test: ["CMD", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5


# networks:
#   kafka-network:
#     driver: bridge
#   airflow-kafka:
#     external: true